name: Lint
on: pull_request
jobs:
  lint:
    name: Android Lint Checker
    runs-on: ubuntu-latest
    env:
      task: lintDebug
    steps:
      # Removed some steps for brevity
      - name: Check changed modules
        uses: dorny/paths-filter@v2
        id: modules
        with:
          filters: .github/config/file_filter_config.yml

      - name: Set lint gradle task
        id: gradle_task_name
        env:
          changed_modules: ${{ toJson(steps.modules.outputs.changes) }}
        shell: pwsh
        run: .\.github\scripts\gradle-task-setter.ps1

      - name: Run lint
        run: ./gradlew ${{ steps.gradle_task_name.outputs.gradleTask }} --continue

      - name: Create Checkstyle Lint Report
        if: ${{ failure() }}
        run: ./gradlew createCheckstyleLintReport -PgithubWorkspace=$GITHUB_WORKSPACE

      - name: Report with Review Dog
        run: ...